{
 "title": "BackupPlan-Backup",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "trilio_system_info" },
   {
    "name": "Scope",
    "query": "trilio_system_info{cluster=~\"$Cluster\"}"
   },
   {
    "name": "Namespace",
    "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
   },
   { "name": "BackupPlan", "label": "BackupPlan", "query": "label_values(backupplan)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "content": "\n<center><h1> BackupPlans</h1></center>\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 0 },
   "content": "<center><h1> Backups </h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "content": "<center><h1> Target </h1></center>"
  },
  {
   "title": "Total ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (backupplan) (trilio_backupplan_info{backupplan=~\"$BackupPlan\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{backupplan=~\"$BackupPlan\", status=\"Available\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{backupplan=~\"$BackupPlan\", status=\"Error\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (backup) (trilio_backup_info{backupplan=~\"$BackupPlan\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backup_info{backupplan=~\"$BackupPlan\", status=\"Available\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backup_info{backupplan=~\"$BackupPlan\", status=\"Error\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (target) (trilio_target_info{backupplan=~\"$BackupPlan\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (target) (trilio_target_info{backupplan=~\"$BackupPlan\", status=\"Available\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "InProgress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{backupplan=~\"$BackupPlan\", status=\"InProgress\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{backupplan=~\"$BackupPlan\", status=\"Pending\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "InProgress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backup_info{backupplan=~\"$BackupPlan\", status=\"InProgress\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backup_info{backupplan=~\"$BackupPlan\", status=\"Pending\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backup_info{backupplan=~\"$BackupPlan\", status=\"Failed\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (target) (trilio_target_info{backupplan=~\"$BackupPlan\", status=\"Unavailable\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "BackupPlan Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(trilio_backupplan_info{backupplan=~\"$BackupPlan\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}) by (backupplan,namespace, status)"
    }
   ]
  },
  {
   "title": "Backup Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "trilio_backup_info{backupplan=~\"$BackupPlan\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Target Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "avg(trilio_target_info{backupplan=~\"$BackupPlan\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}) by (status, target)"
    }
   ]
  }
 ]
}