{
 "title": "Backup-Restore",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "trilio_system_info" },
   {
    "name": "Scope",
    "query": "trilio_system_info{cluster=~\"$Cluster\"}"
   },
   {
    "name": "Namespace",
    "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
   },
   {
    "name": "Backup",
    "label": "Backup",
    "query": "trilio_backup_info{namespace=~\"$Namespace\"}"
   },
   {
    "name": "Restore",
    "label": "Restore",
    "query": "trilio_restore_info{backup=~\"$Backup\",namespace=~\"$Namespace\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "content": "<center><h1> Backups </h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 11, "y": 0 },
   "content": "\n<center><h1>Restores</h1></center>\n\n\n\n"
  },
  {
   "title": "Total ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (backup) (trilio_backup_info{backup=~\"$Backup\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backup_info{backup=~\"$Backup\", status=\"Available\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "InProgress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backup_info{backup=~\"$Backup\", status=\"InProgress\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (restore) (trilio_restore_info{backup=~\"$Backup\", restore=~\"$Restore\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_restore_info{backup=~\"$Backup\", restore=~\"$Restore\", status=\"Completed\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "InProgress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_restore_info{backup=~\"$Backup\", restore=~\"$Restore\", status=\"InProgress\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backup_info{backup=~\"$Backup\", status=\"Pending\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backup_info{backup=~\"$Backup\", status=\"Failed\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_backup_info{backup=~\"$Backup\", status=\"Error\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_restore_info{backup=~\"$Backup\",  restore=~\"$Restore\", status=\"Error\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_restore_info{backup=~\"$Backup\", restore=~\"$Restore\", status=\"Pending\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(trilio_restore_info{backup=~\"$Backup\", restore=~\"$Restore\", status=\"Failed\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": " Backup Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg(trilio_backup_status_percentage{backup=~\"$Backup\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}) by (status, backup)",
     "legendFormat": "{{backup}} {{status}}"
    }
   ]
  },
  {
   "title": " Restore Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg(trilio_restore_status_percentage{backup=~\"$Backup\", restore=~\"$Restore\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}) by (status, restore)",
     "legendFormat": "{{restore}} {{status}}"
    }
   ]
  },
  {
   "title": "Top 5 Backup Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "topk(5,avg(trilio_backup_completed_duration{backup=~\"$Backup\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}) by (backup, start_ts) )",
     "legendFormat": "{{backup}} start_time -> {{start_ts}}"
    }
   ]
  },
  {
   "title": "Restore Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "topk(5,avg(trilio_restore_completed_duration{backup=~\"$Backup\" ,restore=~\"$Restore\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}) by (restore, start_ts) )",
     "legendFormat": "{{restore}} start_time -> {{start_ts}}"
    }
   ]
  },
  {
   "title": " Backup Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(trilio_backup_storage{backup=~\"$Backup\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}) by (backup)",
     "legendFormat": "{{backup}}"
    }
   ]
  }
 ]
}