{
 "title": "Target",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "trilio_system_info" },
   {
    "name": "Scope",
    "query": "trilio_system_info{cluster=~\"$Cluster\"}"
   },
   {
    "name": "Namespace",
    "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
   },
   {
    "name": "Target",
    "label": "Target",
    "query": "trilio_target_info{namespace=~\"$Namespace\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "content": "<center><h1>Targets</h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "content": "<center><h1>BackupPlans</h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "content": "<center><h1>Backups</h1></center>"
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (target)(trilio_target_info{status=~\"Available\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (target) (trilio_target_info{status=~\"Unavailable\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 2 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(trilio_backup_storage_gb{target=~\"$Target\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (backupplan) (trilio_backupplan_info{target=~\"$Target\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Available ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (backupplan) (trilio_backupplan_info{target=~\"$Target\", status=~\"Available\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (backup) (trilio_backup_info{target=~\"$Target\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (backup) (trilio_backup_info{target=~\"$Target\", status=\"Available\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Target Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg(trilio_target_info{target=~\"$Target\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}) by (target,status, vendor,vendorType)"
    }
   ]
  },
  {
   "title": "BackupPlan Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "trilio_backupplan_info{target=~\"$Target\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Target Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(trilio_backup_storage{target=~\"$Target\", namespace=~\"$Namespace\",cluster=~\"$Cluster\"}) by (backup)",
     "legendFormat": "{{backup}}"
    }
   ]
  },
  {
   "title": "Backup Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "trilio_backup_info{target=~\"$Target\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  }
 ]
}